"""
CREATE DATABASE trivia;

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR (255) NOT NULL
);


CREATE TABLE questions
(
    question_id    SERIAL PRIMARY KEY,
    category_id    INT REFERENCES categories (id),
    question_text  TEXT                                                   NOT NULL,
    answer_a       TEXT                                                   NOT NULL,
    answer_b       TEXT                                                   NOT NULL,
    answer_c       TEXT                                                   NOT NULL,
    answer_d       TEXT                                                   NOT NULL,
    correct_answer CHAR(1) CHECK (correct_answer IN ('a', 'b', 'c', 'd')) NOT NULL
);

CREATE TABLE answers (
    id SERIAL PRIMARY KEY,
    question_id INT REFERENCES questions(question_id),
    answer_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL
);


CREATE TABLE players (
    id SERIAL PRIMARY KEY,
    username VARCHAR (255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE player_answers
(
    id SERIAL PRIMARY KEY,
    player_id INT REFERENCES players(id),
    question_id INT REFERENCES questions(question_id),
    selected_answer_id INT REFERENCES answers(id),
    is_correct BOOLEAN,
    answered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE high_scores
(
    id         SERIAL PRIMARY KEY,
    player_id  INT REFERENCES players (id),
    score      INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (name) VALUES
('Classical Music Theory'),
('Composers Biography'),
('Opera World'),
('General Knowledge');

INSERT INTO questions (category_id, question_text, answer_a, answer_b, answer_c, answer_d, correct_answer) VALUES

-- Classical Music Theory (category_id = 1)

(1, 'What is the term for a half step in music theory?', 'Tone', 'Semitone', 'Scale', 'Interval', 'b'),
(1, 'What does the term "legato" mean?', 'Smoothly', 'Rapidly', 'With pauses', 'Softly', 'a'),
(1, 'What does "forte" mean in music?', 'Loud', 'Soft', 'Fast', 'Slow', 'a'),
(1, 'What is the scale of C major?', 'C D E F G A B', 'C D E F G A B C', 'C D E F G A', 'C D E F G', 'b'),
(1, 'Which symbol indicates a sharp note?', '♭', '♮', '♯', '♬', 'c'),
(1, 'What is a whole note in time value?', '1 beat', '2 beats', '4 beats', '8 beats', 'c'),
(1, 'What is the term for increasing the volume of a note?', 'Diminuendo', 'Crescendo', 'Forte', 'Piano', 'b'),
(1, 'How many beats are in a measure of 4/4 time?', '2', '3', '4', '5', 'c'),
(1, 'What is a key signature?', 'The time signature of a piece', 'Indication of dynamics', 'The sharps or flats in a piece', 'The tempo of a piece', 'c'),
(1, 'What does "piano" mean in music?', 'Loud', 'Soft', 'Fast', 'Slow', 'b'),
(1, 'What is the interval between C and E?', 'Major second', 'Minor third', 'Major third', 'Perfect fourth', 'c'),
(1, 'What is a rest in music?', 'A pause in the music', 'A loud section', 'A repeated note', 'A fast passage', 'a'),
(1, 'What is the term for playing music smoothly?', 'Staccato', 'Legato', 'Piano', 'Forte', 'b'),
(1, 'What does "allegro" mean?', 'Slow', 'Fast', 'Moderate', 'Very fast', 'b'),
(1, 'What is the tonic of the C major scale?', 'C', 'D', 'E', 'F', 'a'),
(1, 'What is a time signature?', 'The tempo of a piece', 'Indicates the number of beats per measure', 'The key of a piece', 'The dynamics of a piece', 'b'),
(1, 'What is a major scale?', 'A scale with whole and half steps', 'A scale that sounds happy', 'A scale that sounds sad', 'A scale with all flats', 'b'),
(1, 'Which note is the tonic in the G major scale?', 'A', 'B', 'G', 'D', 'c'),
(1, 'What is syncopation?', 'A regular rhythm', 'An off-beat rhythm', 'A repeated phrase', 'A dynamic marking', 'b'),
(1, 'What is the term for a gradual decrease in volume?', 'Crescendo', 'Diminuendo', 'Forte', 'Piano', 'b'),
(1, 'What does "staccato" mean?', 'Smoothly', 'Separated', 'Loudly', 'Softly', 'b'),
(1, 'What is a harmonic interval?', 'Two notes played together', 'A single note', 'A rest', 'A dynamic marking', 'a'),
(1, 'How many sharps are in the key of E major?', '1', '2', '3', '4', 'a'),
(1, 'What is a diminished chord?', 'A happy chord', 'A sad chord', 'A chord with a minor third', 'A chord with a perfect fifth', 'c'),
(1, 'What is the primary characteristic of a "symphony"?', 'It is written for solo instruments.', 'It is a large-scale orchestral work typically in four movements.', 'It is a vocal work for choir and orchestra.', 'It is a short piece for piano.', 'b'),
(1, 'What is an octave?', 'The distance between two notes with the same name', 'A type of chord', 'A musical scale', 'A form of rest', 'a'),
(1, 'What does "ritardando" mean?', 'Gradually slowing down', 'Gradually getting faster', 'A loud passage', 'A soft passage', 'a'),
(1, 'Which of the following is a natural minor scale?', 'A B C D E F G', 'A B C D E F# G', 'A B C D# E F# G#', 'A B C# D E F# G', 'a'),
(1, 'What is a motif?', 'A recurring musical theme', 'A type of instrument', 'A rest', 'A dynamic marking', 'a'),
(1, 'What does "fortissimo" mean?', 'Very soft', 'Soft', 'Loud', 'Very loud', 'd'),
(1, 'What is the term for playing notes sharply?', 'Legato', 'Staccato', 'Piano', 'Forte', 'b'),
(1, 'Which symbol indicates a flat note?', '♯', '♭', '♮', '♬', 'b'),
(1, 'What is the term for a musical composition for a solo instrument?', 'Sonata', 'Symphony', 'Concerto', 'Suite', 'a'),
(1, 'What is the term for the speed of music?', 'Tempo', 'Dynamics', 'Pitch', 'Rhythm', 'a'),
(1, 'What does a treble clef indicate?', 'High pitch', 'Low pitch', 'Rhythm', 'Dynamics', 'a'),
(1, 'Which note is the first in the chromatic scale?', 'C', 'A', 'G', 'D', 'b'),
(1, 'What is a scale that includes both whole and half steps?', 'Diatonic scale', 'Chromatic scale', 'Pentatonic scale', 'Whole-tone scale', 'a'),
(1, 'Which of the following is a compound time signature?', '3/4', '4/4', '6/8', '2/4', 'c'),
(1, 'What does "mp" stand for in music dynamics?', 'Moderately loud', 'Moderately soft', 'Very loud', 'Very soft', 'b'),
(1, 'What is the distance between two notes called?', 'Interval', 'Chord', 'Scale', 'Key', 'a'),
(1, 'Which of the following is a type of scale?', 'Major', 'Minor', 'Chromatic', 'All of the above', 'd'),
(1, 'What does a fermata indicate?', 'Hold the note longer', 'Play softly', 'Repeat the section', 'Change the tempo', 'a'),
(1, 'What is the term for a repeated musical phrase in a piece?', 'Theme', 'Variation', 'Motif', 'Coda', 'c'),
(1, 'Which symbol represents a natural note?', '♯', '♭', '♮', '♬', 'c'),
(1, 'What is the term for playing a note softly?', 'Piano', 'Forte', 'Legato', 'Staccato', 'a'),
(1, 'How many sharps are in the key of G major?', '1', '2', '3', '4', 'a'),
(1, 'What is the interval between E and G?', 'Minor third', 'Major third', 'Perfect fourth', 'Major second', 'a'),
(1, 'What does "dynamics" refer to in music?', 'Loudness and softness', 'Speed', 'Pitch', 'Texture', 'a'),
(1, 'Which of the following represents a half note?', '♩', '𝅗𝅥', '𝅘𝅥', '𝅘𝅗', 'b'),
(1, 'What does "a tempo" mean?', 'Return to the original tempo', 'Slow down', 'Speed up', 'Play softly', 'a'),
(1, 'Which of the following is a minor scale?', 'C D E F G A B', 'A B C D E F G', 'D E F# G A B C', 'F G A B C D E', 'c'),
(1, 'What is a "chord progression"?', 'A series of chords played in sequence', 'A type of scale', 'A musical form', 'A melody', 'a'),
(1, 'Which of the following is not a woodwind instrument?', 'Flute', 'Clarinet', 'Trumpet', 'Oboe', 'c'),
(1, 'What does "Crescendo" indicate?', 'Gradually getting louder', 'Gradually getting softer', 'Maintaining volume', 'A sudden change in dynamics', 'a'),
(1, 'What is the term for the distance between two notes?', 'Interval', 'Octave', 'Scale', 'Chord', 'a'),
(1, 'How many notes are in a chromatic scale?', '7', '12', '10', '14', 'b'),
(1, 'What does "a tempo" mean?', 'Slow down', 'Return to the original tempo', 'Speed up', 'Pause', 'b'),
(1, 'Which of the following is a major scale?', 'A B C D E F# G#', 'A B C D E F G', 'A B C D E F# G', 'A B C D# E F# G#', 'c'),
(1, 'What is the term for a piece of music for a solo instrument?', 'Sonata', 'Concerto', 'Symphony', 'Chamber music', 'a'),
(1, 'How many beats does a half note receive in 4/4 time?', '1', '2', '3', '4', 'b'),
(1, 'What is the symbol for a natural note?', '♭', '♯', '♮', '𝄞', 'c'),
(1, 'What does "pizzicato" refer to?', 'Plucking strings', 'Playing softly', 'Playing loudly', 'Bow technique', 'a'),
(1, 'What is the term for the speed of a piece of music?', 'Dynamics', 'Tempo', 'Style', 'Meter', 'b'),
(1, 'What is a scale that consists of only whole steps called?', 'Diatonic scale', 'Whole-tone scale', 'Chromatic scale', 'Pentatonic scale', 'b'),
(1, 'How many sharps are in the key of B major?', '3', '5', '2', '4', 'a'),
(1, 'What is the term for a repeated section in music?', 'Verse', 'Refrain', 'Chorus', 'Bridge', 'c'),
(1, 'What does "da capo" mean in music?', 'From the beginning', 'To the end', 'Play softly', 'Play loudly', 'a'),
(1, 'Which term describes the loudness or softness of music?', 'Dynamics', 'Articulation', 'Tempo', 'Rhythm', 'a'),
(1, 'What is a minor scale?', 'A scale with a lowered third', 'A scale with all whole steps', 'A scale that sounds happy', 'A scale with only black keys', 'a'),
(1, 'Which interval is known as a major third?', 'C to E', 'C to D', 'C to F', 'C to G', 'a'),
(1, 'What does "fermata" indicate?', 'Pause', 'Repeat', 'Play loudly', 'Play softly', 'a'),
(1, 'Which term describes a gradual decrease in volume?', 'Crescendo', 'Diminuendo', 'Forte', 'Piano', 'b'),
(1, 'What is a triad?', 'A chord with three notes', 'A scale with three notes', 'A type of rest', 'A dynamic marking', 'a'),
(1, 'What does "tempo rubato" mean?', 'Steady tempo', 'Flexible tempo', 'Slow tempo', 'Fast tempo', 'b'),
(1, 'Which symbol indicates a double sharp note?', '♯', '♭', '𝄪', '♮', 'c'),
(1, 'What is the term for playing a piece in a lively manner?', 'Allegro', 'Adagio', 'Andante', 'Lento', 'a'),
(1, 'What is the term for a series of notes that create a musical idea?', 'Motif', 'Theme', 'Chord', 'Scale', 'b'),
(1, 'How many beats are in a measure of 3/4 time?', '2', '3', '4', '5', 'b'),
(1, 'What does "staccato" mean?', 'Smoothly', 'Separated', 'Loudly', 'Softly', 'b'),
(1, 'Which term describes the organization of beats into measures?', 'Rhythm', 'Meter', 'Tempo', 'Dynamics', 'b'),

-- Classical Music Theory (category_id = 2)

(2, 'Who is known for composing "Pachelbel’s Canon"?', 'Pachelbel', 'Bach', 'Vivaldi', 'Handel', 'a'),
(2, 'Which composer created the operatic masterpiece "Carmen"?', 'Bizet', 'Verdi', 'Puccini', 'Wagner', 'a'),
(2, 'Who composed "The Rite of Spring"?', 'Stravinsky', 'Debussy', 'Schoenberg', 'Prokofiev', 'a'),
(2, 'Which composer is famous for his "Italian Symphony"?', 'Mendelssohn', 'Brahms', 'Dvořák', 'Schumann', 'a'),
(2, 'Who wrote the "Enigma Variations"?', 'Elgar', 'Holst', 'Berlioz', 'Bach', 'a'),
(2, 'Which composer is known for the ballet "Swan Lake"?', 'Tchaikovsky', 'Prokofiev', 'Stravinsky', 'Brahms', 'a'),
(2, 'Who composed the "Piano Concerto No. 21" known for its second movement?', 'Mozart', 'Beethoven', 'Chopin', 'Rachmaninoff', 'a'),
(2, 'Which composer is associated with the term "minimalism"?', 'Reich', 'Glass', 'Adams', 'All of the above', 'd'),
(2, 'Who wrote the "Overture to the Marriage of Figaro"?', 'Mozart', 'Haydn', 'Berlioz', 'Verdi', 'a'),
(2, 'Which composer created "The Planets" suite?', 'Holst', 'Vaughan Williams', 'Elgar', 'Delius', 'a'),
(2, 'Who is known for the piece "The Entertainer"?', 'Joplin', 'Gershwin', 'Scott', 'Ellington', 'a'),
(2, 'Which composer wrote the famous "Moonlight Sonata"?', 'Beethoven', 'Chopin', 'Liszt', 'Brahms', 'a'),
(2, 'Who composed the "Carnival of the Animals"?', 'Saint-Saëns', 'Debussy', 'Ravel', 'Faure', 'a'),
(2, 'Which composer is known for his "American" works, like "Appalachian Spring"?', 'Copland', 'Gershwin', 'Bernstein', 'Ives', 'a'),
(2, 'Who wrote "Largo" from "Xerxes"?', 'Handel', 'Vivaldi', 'Bach', 'Purcell', 'a'),
(2, 'Which composer is famous for the song cycle "Winterreise"?', 'Schubert', 'Schumann', 'Brahms', 'Wolf', 'a'),
(2, 'Who composed the "Adagio in G minor"?', 'Albinoni', 'Bach', 'Vivaldi', 'Corelli', 'a'),
(2, 'Which composer is known for the symphony "From the New World"?', 'Dvořák', 'Sibelius', 'Mahler', 'Elgar', 'a'),
(2, 'Who wrote the famous "Four Last Songs"?', 'Strauss', 'Brahms', 'Mahler', 'Webern', 'a'),
(2, 'Which composer is noted for his contributions to film scores, including "Star Wars"?', 'Williams', 'Horner', 'Zimmer', 'Goldsmith', 'a'),
(2, 'Who is known for the "The Magic Flute"?', 'Mozart', 'Haydn', 'Rossini', 'Verdi', 'a'),
(2, 'Which composer wrote "Symphony No. 5 in C minor"?', 'Beethoven', 'Mahler', 'Tchaikovsky', 'Brahms', 'a'),
(2, 'Who composed "Boléro"?', 'Ravel', 'Debussy', 'Chopin', 'Stravinsky', 'a'),
(2, 'Which composer is known for the "Brandenburg Concertos"?', 'Bach', 'Telemann', 'Handel', 'Vivaldi', 'a'),
(2, 'Who wrote "Rhapsody in Blue"?', 'Gershwin', 'Copland', 'Bernstein', 'Joplin', 'a'),
(2, 'Which composer created the famous "Sicilienne"?', 'Fauré', 'Debussy', 'Mendelssohn', 'Ravel', 'a'),
(2, 'Who composed the opera "Aida"?', 'Verdi', 'Puccini', 'Wagner', 'Bizet', 'a'),
(2, 'Which composer is associated with the symphonic poem "Till Eulenspiegel"?', 'Strauss', 'Sibelius', 'Dvořák', 'Brahms', 'a'),
(2, 'Who wrote "The Firebird"?', 'Stravinsky', 'Prokofiev', 'Tchaikovsky', 'Ravel', 'a'),
(2, 'Which composer is known for "Eine kleine Nachtmusik"?', 'Mozart', 'Haydn', 'Beethoven', 'Brahms', 'a'),
(2, 'Who composed the "Liebestraum"?', 'Liszt', 'Chopin', 'Schumann', 'Brahms', 'a'),
(2, 'Which composer is famous for "The Nutcracker"?', 'Tchaikovsky', 'Mendelssohn', 'Prokofiev', 'Brahms', 'a'),
(2, 'Who wrote the "Cello Suites"?', 'Bach', 'Vivaldi', 'Haydn', 'Schumann', 'a'),
(2, 'Which composer is known for "Carmina Burana"?', 'Orff', 'Stravinsky', 'Berg', 'Schoenberg', 'a'),
(2, 'Who composed "Symphony No. 9" in D minor, "Choral"?', 'Beethoven', 'Mahler', 'Brahms', 'Dvořák', 'a'),
(2, 'Which composer is known for the song "Somewhere Over the Rainbow"?', 'Arlen', 'Gershwin', 'Bernstein', 'Rodgers', 'a'),
(2, 'Who wrote the "Fifth Symphony of the Unfinished"?', 'Schubert', 'Beethoven', 'Brahms', 'Dvořák', 'a'),
(2, 'Which composer created the work "Pines of Rome"?', 'Respighi', 'Puccini', 'Verdi', 'Tchaikovsky', 'a'),
(2, 'Who is known for the "Variations on a Theme by Haydn"?', 'Brahms', 'Schumann', 'Mahler', 'Dvořák', 'a'),
(2, 'Which composer is famous for the opera "La Traviata"?', 'Verdi', 'Puccini', 'Bizet', 'Wagner', 'a'),
(2, 'Which composer is known for the ballet "The Firebird"?', 'Stravinsky', 'Tchaikovsky', 'Prokofiev', 'Ballets Russes', 'a'),
(2, 'Who composed the famous "Clair de Lune"?', 'Debussy', 'Ravel', 'Chopin', 'Liszt', 'a'),
(2, 'Which composer is celebrated for his "Symphony No. 7" in E minor, known as the "Leningrad Symphony"?', 'Shostakovich', 'Prokofiev', 'Stravinsky', 'Rachmaninoff', 'a'),
(2, 'Who wrote the opera "The Magic Flute"?', 'Mozart', 'Haydn', 'Berlioz', 'Verdi', 'a'),
(2, 'Which composer is known for his "Hungarian Dances"?', 'Brahms', 'Liszt', 'Kodály', 'Bartók', 'a'),
(2, 'Who composed the "Adagio for Strings"?', 'Barber', 'Copland', 'Gershwin', 'Ives', 'a'),
(2, 'Which composer is known for the operatic work "The Flying Dutchman"?', 'Wagner', 'Verdi', 'Puccini', 'Mozart', 'a'),
(2, 'Who wrote the famous "Brandenburg Concertos"?', 'Bach', 'Handel', 'Vivaldi', 'Haydn', 'a'),
(2, 'Which composer is known for "The Four Seasons"?', 'Vivaldi', 'Bach', 'Beethoven', 'Haydn', 'a'),
(2, 'Who composed the "Piano Concerto in G major"?', 'Ravel', 'Debussy', 'Mozart', 'Chopin', 'a'),
(2, 'Which composer is associated with the "Eroica Symphony"?', 'Beethoven', 'Brahms', 'Haydn', 'Schubert', 'a'),
(2, 'Who wrote the opera "Otello"?', 'Verdi', 'Puccini', 'Wagner', 'Bizet', 'a'),
(2, 'Which composer is known for the "Cinq Incantations"?', 'Dukas', 'Debussy', 'Ravel', 'Stravinsky', 'a'),
(2, 'Who composed the "Fifth Symphony" with the famous "Fate" motif?', 'Beethoven', 'Mahler', 'Tchaikovsky', 'Dvořák', 'a'),
(2, 'Which composer wrote the "Serenade for Strings"?', 'Tchaikovsky', 'Dvořák', 'Elgar', 'Mendelssohn', 'a'),
(2, 'Who is known for the opera "Rigoletto"?', 'Verdi', 'Puccini', 'Mozart', 'Wagner', 'a'),
(2, 'Which composer is famous for the "Symphony Fantastique"?', 'Berlioz', 'Debussy', 'Ravel', 'Stravinsky', 'a'),
(2, 'Who composed "Gymnopédies"?', 'Satie', 'Debussy', 'Fauré', 'Ravel', 'a'),
(2, 'Which composer is recognized for his work "La Traviata"?', 'Verdi', 'Puccini', 'Bizet', 'Wagner', 'a'),
(2, 'Who wrote the "Sonata for Two Pianos and Percussion"?', 'Béla Bartók', 'Stravinsky', 'Debussy', 'Prokofiev', 'a'),
(2, 'Which composer is known for his operas "The Marriage of Figaro" and "Don Giovanni"?', 'Mozart', 'Verdi', 'Puccini', 'Wagner', 'a'),
(2, 'Who is often referred to as the "German Beethoven"?', 'Brahms', 'Schumann', 'Haydn', 'Mendelssohn', 'a'),
(2, 'Which composer is famous for the "Moonlight Sonata"?', 'Beethoven', 'Chopin', 'Liszt', 'Bach', 'a'),
(2, 'Who composed the opera "Tosca"?', 'Puccini', 'Verdi', 'Bizet', 'Wagner', 'a'),
(2, 'Which composer wrote the "Piano Concerto No. 1" in E minor?', 'Chopin', 'Liszt', 'Beethoven', 'Rachmaninoff', 'a'),
(2, 'Who is known for the symphonic poem "Also sprach Zarathustra"?', 'Strauss', 'Brahms', 'Wagner', 'Mahler', 'a'),
(2, 'Which composer created the famous ballet "Swan Lake"?', 'Tchaikovsky', 'Stravinsky', 'Prokofiev', 'Ravel', 'a'),
(2, 'Who composed the oratorio "The Creation"?', 'Haydn', 'Handel', 'Bach', 'Mozart', 'a'),
(2, 'Which composer is associated with the "Piano Sonata No. 8", known as the "Pathétique"?', 'Beethoven', 'Chopin', 'Mozart', 'Schumann', 'a'),
(2, 'Who wrote the "Symphony No. 9" known as the "Choral Symphony"?', 'Beethoven', 'Brahms', 'Dvořák', 'Mahler', 'a'),
(2, 'Which composer is known for his work "The Barber of Seville"?', 'Rossini', 'Verdi', 'Puccini', 'Wagner', 'a'),
(2, 'Who is the composer of the "Unfinished Symphony"?', 'Schubert', 'Brahms', 'Mahler', 'Beethoven', 'a'),
(2, 'Which composer is famous for his "Requiem"?', 'Mozart', 'Brahms', 'Verdi', 'Fauré', 'a'),
(2, 'Who wrote the opera "Madama Butterfly"?', 'Puccini', 'Verdi', 'Bizet', 'Wagner', 'a'),
(2, 'Which composer is known for the "Carmen"?', 'Bizet', 'Verdi', 'Puccini', 'Wagner', 'a'),
(2, 'Who composed "The Well-Tempered Clavier"?', 'Bach', 'Beethoven', 'Chopin', 'Liszt', 'a'),
(2, 'Which composer wrote the "New World Symphony"?', 'Dvořák', 'Brahms', 'Tchaikovsky', 'Mahler', 'a'),
(2, 'Who is known for the operatic masterpiece "Aida"?', 'Verdi', 'Puccini', 'Bizet', 'Wagner', 'a'),
(2, 'Which composer created the "Violin Concerto in E minor"?', 'Mendelssohn', 'Brahms', 'Beethoven', 'Vivaldi', 'a'),
(2, 'Who composed the famous "Carnival of the Animals"?', 'Saint-Saëns', 'Debussy', 'Ravel', 'Stravinsky', 'a'),

-- Classical Music Theory (category_id = 3)

(3, 'Which composer wrote "Carmen"?', 'Bizet', 'Verdi', 'Puccini', 'Wagner', 'a'),
(3, 'What is the setting of "The Magic Flute"?', 'Ancient Egypt', 'Medieval Europe', 'Ancient Greece', 'Modern America', 'a'),
(3, 'Who is the main character in "La Traviata"?', 'Violetta', 'Carmen', 'Mimi', 'Desdemona', 'a'),
(3, 'Which opera features the aria "Nessun dorma"?', 'Turandot', 'La Bohème', 'Madama Butterfly', 'Aida', 'a'),
(3, 'What is the name of the opera house in Sydney?', 'Sydney Opera House', 'Royal Opera House', 'Teatro alla Scala', 'Metropolitan Opera', 'a'),
(3, 'Who composed "The Ring Cycle"?', 'Wagner', 'Verdi', 'Mozart', 'Puccini', 'a'),
(3, 'Which opera tells the story of a young woman who sacrifices herself for love in a tragic ending?', 'Madama Butterfly', 'Carmen', 'Don Giovanni', 'Rigoletto', 'a'),
(3, 'In which opera does the character Don Giovanni appear?', 'Don Giovanni', 'The Marriage of Figaro', 'Cosi fan tutte', 'Aida', 'a'),
(3, 'What is the primary language of "La Bohème"?', 'Italian', 'French', 'German', 'English', 'a'),
(3, 'Which opera features the "Brindisi" drinking song?', 'La Traviata', 'Carmen', 'Tosca', 'Madama Butterfly', 'a'),
(3, 'Who is the composer of "The Barber of Seville"?', 'Rossini', 'Donizetti', 'Verdi', 'Puccini', 'a'),
(3, 'What is the main theme of "Aida"?', 'Love and war', 'Betrayal', 'Redemption', 'Jealousy', 'a'),
(3, 'Which opera includes the characters Rodolfo and Mimi?', 'La Bohème', 'Madama Butterfly', 'Carmen', 'Tosca', 'a'),
(3, 'In which opera is the character of the Witch prominent?', 'Hansel and Gretel', 'The Magic Flute', 'Carmen', 'Rigoletto', 'a'),
(3, 'What is the name of the famous duet from "The Pearl Fishers"?', 'Au fond du temple saint', 'Libiamo ne’ lieti calici', 'Dio che nell’alma infondere', 'O mio babbino caro', 'a'),
(3, 'Which opera is set during the French Revolution?', 'Dialogues des Carmélites', 'Carmen', 'Les Misérables', 'Don Carlos', 'a'),
(3, 'What is the significance of the "Chorus of the Hebrew Slaves"?', 'From Nabucco', 'From Aida', 'From Tosca', 'From Rigoletto', 'a'),
(3, 'Which opera is known for the aria "O mio babbino caro"?', 'Gianni Schicchi', 'La Bohème', 'Carmen', 'Rigoletto', 'a'),
(3, 'Who composed "Tosca"?', 'Puccini', 'Verdi', 'Wagner', 'Mozart', 'a'),
(3, 'What is the setting of "Madama Butterfly"?', 'Japan', 'Italy', 'France', 'Germany', 'a'),
(3, 'Which opera features the character Figaro?', 'The Marriage of Figaro', 'Carmen', 'Tosca', 'La Traviata', 'a'),
(3, 'What is the primary setting of "Rigoletto"?', 'Mantua', 'Paris', 'Venice', 'Seville', 'a'),
(3, 'Who composed "Madama Butterfly"?', 'Puccini', 'Verdi', 'Bizet', 'Mozart', 'a'),
(3, 'Which opera is based on the play "La Dame aux Camélias"?', 'La Traviata', 'Carmen', 'Don Giovanni', 'Aida', 'a'),
(3, 'In which opera does the character Turandot appear?', 'Turandot', 'La Bohème', 'Carmen', 'Aida', 'a'),
(3, 'Which opera includes the famous "Habanera"?', 'Carmen', 'Tosca', 'La Traviata', 'Rigoletto', 'a'),
(3, 'What does the title "Die Fledermaus" mean in English?', 'The Bat', 'The Bird', 'The Fox', 'The Lion', 'a'),
(3, 'Who is the composer of "Aida"?', 'Verdi', 'Puccini', 'Wagner', 'Mozart', 'a'),
(3, 'Which opera is known for the aria "La donna è mobile"?', 'Rigoletto', 'Carmen', 'Tosca', 'Madama Butterfly', 'a'),
(3, 'In which opera do we find the character of Escamillo?', 'Carmen', 'Don Giovanni', 'The Magic Flute', 'La Traviata', 'a'),
(3, 'Which composer is associated with the verismo style in opera?', 'Mascagni', 'Rossini', 'Donizetti', 'Wagner', 'a'),
(3, 'What is the main theme of "Tosca"?', 'Love and betrayal', 'Revenge', 'Redemption', 'Adventure', 'a'),
(3, 'Which opera features the character of the Queen of the Night?', 'The Magic Flute', 'Carmen', 'Aida', 'Don Giovanni', 'a'),
(3, 'What is the setting of "The Flying Dutchman"?', 'Aboard a ship', 'A palace', 'A village', 'A forest', 'a'),
(3, 'Who is the librettist of "Carmen"?', 'Henri Meilhac and Ludovic Halévy', 'Giuseppe Verdi', 'Wolfgang Amadeus Mozart', 'Richard Wagner', 'a'),
(3, 'Which opera is known for its use of minimalism?', 'Nixon in China', 'La Traviata', 'Carmen', 'Madama Butterfly', 'a'),
(3, 'In which opera does the character of Gilda appear?', 'Rigoletto', 'La Bohème', 'Carmen', 'Tosca', 'a'),
(3, 'What is the premise of "The Magic Flute"?', 'A quest for enlightenment', 'A tragic love story', 'A tale of revenge', 'A historical drama', 'a'),
(3, 'Which opera includes the aria "O patria mia"?', 'Aida', 'Tosca', 'Carmen', 'Madama Butterfly', 'a'),
(3, 'What is the significance of the "Carmen" setting in Spain?', 'Cultural backdrop', 'Historical accuracy', 'Dramatic tension', 'All of the above', 'd'),
(3, 'Which opera opens with the sound of a stormy sea?', 'The Flying Dutchman', 'La Traviata', 'Carmen', 'Madama Butterfly', 'a'),
(3, 'In what opera does a character famously declare, "I am your father"?', 'Don Giovanni', 'The Magic Flute', 'Carmen', 'Turandot', 'b'),
(3, 'What animal is featured prominently in "The Tales of Hoffmann"?', 'A cat', 'A bird', 'A doll', 'A mouse', 'c'),
(3, 'Which opera features a duel over a woman’s honor?', 'Rigoletto', 'Tosca', 'Carmen', 'Madama Butterfly', 'a'),
(3, 'In which opera does a character disguise themselves as a man to pursue love?', 'Carmen', 'The Magic Flute', 'Cenerentola', 'Madama Butterfly', 'c'),
(3, 'What element of nature is central to the plot of "Turandot"?', 'Fire', 'Ice', 'Water', 'Earth', 'b'),
(3, 'Which opera features a love story interrupted by a war?', 'Aida', 'La Bohème', 'Carmen', 'Rigoletto', 'a'),
(3, 'In "The Barber of Seville," what is Figaro’s profession?', 'Barber', 'Baker', 'Soldier', 'Merchant', 'a'),
(3, 'Which opera is inspired by a novel by Alexander Dumas?', 'The Count of Monte Cristo', 'Carmen', 'Don Carlos', 'La Traviata', 'a'),
(3, 'In "La Boheme," what profession do the main characters pursue?', 'Artists', 'Merchants', 'Nobles', 'Scientists', 'a'),
(3, 'What is the significance of the character of Mimi in "La Bohème"?', 'Symbol of love and loss', 'Symbol of hope', 'Symbol of wealth', 'Symbol of betrayal', 'a'),
(3, 'Which opera features the famous "Flower Duet"?', 'Lakmé', 'Carmen', 'Tosca', 'Madama Butterfly', 'a'),
(3, 'What is the central conflict in "Carmen"?', 'Love and jealousy', 'War and peace', 'Revenge and forgiveness', 'Rich and poor', 'a'),
(3, 'Which opera features a puppet that comes to life?', 'The Tales of Hoffmann', 'Carmen', 'Don Giovanni', 'Aida', 'a'),
(3, 'In which opera does the protagonist have to solve riddles to win love?', 'Turandot', 'Carmen', 'The Magic Flute', 'Rigoletto', 'a'),
(3, 'What dramatic event occurs during the final act of "Tosca"?', 'A murder', 'A wedding', 'A duel', 'A coronation', 'a'),
(3, 'Which opera is set against the backdrop of the Spanish Civil War?', 'Carmen', 'Aida', 'Rigoletto', 'Madama Butterfly', 'a'),
(3, 'In "Aida," what is the relationship between Aida and Radames?', 'Star-crossed lovers', 'Siblings', 'Friends', 'Enemies', 'a'),
(3, 'Which character sings "Nessun dorma"?', 'Calaf', 'Turandot', 'Radames', 'Don José', 'a'),
(3, 'What unique feature does "The Magic Flute" incorporate into its story?', 'Masonic symbolism', 'Historical events', 'Fairy tale elements', 'Modern technology', 'a'),
(3, 'Which opera features a heroine who is turned into a swan?', 'Swan Lake', 'Carmen', 'Rusalka', 'Aida', 'c'),
(3, 'In "Madama Butterfly," what gift does Pinkerton give to Cio-Cio-San?', 'A butterfly', 'A doll', 'A necklace', 'A kimono', 'b'),
(3, 'Which opera is known for the "Habanera" aria?', 'Carmen', 'La Bohème', 'The Magic Flute', 'Rigoletto', 'a'),
(3, 'In which opera does a character famously sing while hanging from a chandelier?', 'The Phantom of the Opera', 'Tosca', 'Carmen', 'Aida', 'a'),
(3, 'What magical element is central to the story of "The Magic Flute"?', 'A magic flute', 'A crystal ball', 'A potion', 'A spell book', 'a'),
(3, 'Which opera tells the tragic story of a courtesan’s unfulfilled love?', 'La Traviata', 'Carmen', 'Tosca', 'Rigoletto', 'a'),
(3, 'In "Don Giovanni," which character seeks revenge from beyond the grave?', 'The Commendatore', 'Don Ottavio', 'Leporello', 'Zerlina', 'a'),
(3, 'What is the setting of "Aida"?', 'Ancient Egypt', 'Renaissance Italy', 'Victorian England', 'Modern France', 'a'),
(3, 'Which opera features a character who is a puppet-maker?', 'The Tales of Hoffmann', 'Carmen', 'La Bohème', 'Madama Butterfly', 'a'),
(3, 'What significant object is central to the plot of "The Ring Cycle"?', 'A ring of power', 'A magic sword', 'A crown', 'A harp', 'a'),
(3, 'In "The Barber of Seville," what is the primary goal of Figaro?', 'To help Rosina elope', 'To win a contest', 'To start a business', 'To become famous', 'a'),
(3, 'Which opera involves a character disguised as a man to gain access to a secret society?', 'The Magic Flute', 'Carmen', 'Aida', 'Rigoletto', 'a'),
(3, 'In "Tosca," what artistic profession is shared by the main characters?', 'They are artists', 'They are musicians', 'They are writers', 'They are actors', 'a'),
(3, 'What event sets the stage for the drama in "Carmen"?', 'A bullfight', 'A wedding', 'A festival', 'A war', 'a'),
(3, 'Which opera includes the character of a queen who challenges the protagonist to answer three riddles?', 'Turandot', 'Carmen', 'Aida', 'Madama Butterfly', 'a'),
(3, 'In "La Traviata," what illness afflicts Violetta?', 'Consumption', 'Malaria', 'Typhoid', 'Tuberculosis', 'a'),
(3, 'What character trait is often associated with the protagonist of "Don Giovanni"?', 'Seductive charm', 'Heroic bravery', 'Unwavering loyalty', 'Noble intentions', 'a'),
(3, 'Which opera features a famous love duet sung on a balcony?', 'Roméo et Juliette', 'La Bohème', 'Rigoletto', 'Carmen', 'a'),
(3, 'In "Aida," what is the nature of the conflict between Radames and Amonasro?', 'Loyalty to their countries', 'A love triangle', 'A battle for power', 'A personal vendetta', 'a'),
(3, 'What unique musical feature is used in "The Magic Flute" to represent wisdom and enlightenment?', 'Recitative', 'Choral harmony', 'Singing in a different key', 'A leitmotif', 'd'),

-- Classical Music Theory (category_id = 4)

(4, 'Who composed the "Four Seasons"?', 'Vivaldi', 'Bach', 'Handel', 'Mozart', 'a'),
(4, 'What is the key signature of Beethoven’s "Moonlight Sonata"?', 'C# minor', 'A major', 'E minor', 'D major', 'a'),
(4, 'Which composer is known for his symphonic poem "Also sprach Zarathustra"?', 'Stravinsky', 'Mahler', 'Strauss', 'Debussy', 'c'),
(4, 'How many symphonies did Beethoven compose?', '5', '7', '9', '11', 'c'),
(4, 'What is the term for a musical composition for a solo instrument accompanied by an orchestra?', 'Concerto', 'Sonata', 'Symphony', 'Suite', 'a'),
(4, 'Who wrote the opera "The Marriage of Figaro"?', 'Mozart', 'Rossini', 'Verdi', 'Puccini', 'a'),
(4, 'What is the primary form of a typical symphony?', 'ABAB', 'ABA', 'Sonata', 'Rondo', 'c'),
(4, 'In what key is Bach’s "Brandenburg Concerto No. 3"?', 'G major', 'D major', 'A major', 'C minor', 'a'),
(4, 'Which instrument is featured prominently in Chopin’s compositions?', 'Violin', 'Piano', 'Cello', 'Flute', 'b'),
(4, 'What is the structure of a classical sonata?', 'Exposition, Development, Recapitulation', 'Verse, Chorus, Bridge', 'Theme and Variations', 'AAB', 'a'),
(4, 'Which work is NOT a symphony by Mahler?', 'Symphony No. 5', 'Symphony No. 9', 'Symphony No. 6', 'Concerto for Orchestra', 'd'),
(4, 'Who is known for composing "The Nutcracker"?', 'Tchaikovsky', 'Prokofiev', 'Stravinsky', 'Rachmaninoff', 'a'),
(4, 'What is a common feature of chamber music?', 'Written for a large orchestra', 'Performed by a small group of musicians', 'Includes vocal parts', 'Has a strict form', 'b'),
(4, 'Which scale consists of five notes?', 'Major', 'Minor', 'Pentatonic', 'Chromatic', 'c'),
(4, 'What is the tempo marking for "Allegro"?', 'Slow', 'Moderate', 'Fast', 'Very fast', 'c'),
(4, 'Which composer is famous for "The Rite of Spring"?', 'Berlioz', 'Debussy', 'Stravinsky', 'Bach', 'c'),
(4, 'What is the highest female singing voice classification?', 'Alto', 'Soprano', 'Mezzo-soprano', 'Contralto', 'b'),
(4, 'Which instrument is known as the "king of instruments"?', 'Piano', 'Violin', 'Organ', 'Flute', 'c'),
(4, 'Who composed the "Peer Gynt" suites?', 'Grieg', 'Sibelius', 'Dvořák', 'Mendelssohn', 'a'),
(4, 'What type of musical piece is a "Nocturne"?', 'A dance', 'A song', 'A piece for night', 'A slow, reflective work', 'd'),
(4, 'Which composer is known for integrating folk melodies into classical music, notably in "Hungarian Dances"?', 'Dvořák', 'Brahms', 'Liszt', 'Bartók', 'b'),
(4, 'In which era was the "cadenza" prominently featured in concertos?', 'Baroque', 'Classical', 'Romantic', 'Modern', 'b'),
(4, 'What is the title of the famous oratorio composed by Handel that celebrates the birth of Jesus?', 'The Messiah', 'The Creation', 'Elijah', 'Israel in Egypt', 'a'),
(4, 'Which famous composer was also a virtuoso pianist and known for his "Etudes"?', 'Chopin', 'Liszt', 'Beethoven', 'Schumann', 'a'),
(4, 'What is a "lied" in the context of classical music?', 'A choral work', 'A German art song', 'A symphonic poem', 'An opera aria', 'b'),
(4, 'Which musical form features a main theme that is repeated and varied, often found in jazz?', 'Theme and Variations', 'Rondo', 'Sonata', 'Fugue', 'a'),
(4, 'What instrument did J.S. Bach play as his primary instrument?', 'Violin', 'Organ', 'Cello', 'Trumpet', 'b'),
(4, 'Who wrote the famous opera "Carmen"?', 'Verdi', 'Puccini', 'Bizet', 'Wagner', 'c'),
(4, 'What is the primary scale used in blues music?', 'Major', 'Minor', 'Pentatonic', 'Blues scale', 'd'),
(4, 'Which piece is often referred to as "the greatest symphony ever written"?', 'Symphony No. 5', 'Symphony No. 9', 'Symphony No. 7', 'Symphony No. 40', 'b'),
(4, 'What term describes a musical piece that is meant to evoke a specific scene or story?', 'Programmatic music', 'Absolute music', 'Sonata form', 'Variations', 'a'),
(4, 'Which composer is known for his contributions to film music, including "Star Wars" and "Jaws"?', 'Horner', 'Williams', 'Zimmer', 'Elfman', 'b'),
(4, 'What is the name of the famous ballet composed by Tchaikovsky featuring the "Dance of the Sugar Plum Fairy"?', 'Swan Lake', 'The Nutcracker', 'Sleeping Beauty', 'Giselle', 'b'),
(4, 'In music, what does "forte" indicate?', 'Soft', 'Loud', 'Moderate', 'Fast', 'b'),
(4, 'Which composer is famous for using unconventional time signatures, like in "Take Five"?', 'Gershwin', 'Brubeck', 'Ellington', 'Coltrane', 'b'),
(4, 'What kind of ensemble typically performs a "string quartet"?', 'Soloist and piano', 'Four string players', 'Chorus and orchestra', 'Large symphonic orchestra', 'b'),
(4, 'Which musical era is characterized by the use of dissonance and atonality?', 'Classical', 'Romantic', '20th Century', 'Baroque', 'c'),
(4, 'What is the primary difference between an opera and a musical?', 'Use of spoken dialogue', 'Type of music', 'Orchestration', 'Length of performance', 'a'),
(4, 'Who is often referred to as the "Father of the Symphony"?', 'Haydn', 'Mozart', 'Beethoven', 'Schubert', 'a'),
(4, 'What is the primary instrument in a traditional jazz trio?', 'Piano', 'Trumpet', 'Drums', 'Bass', 'a'),
(4, 'What is the musical term for a rapid alternation between two notes, often used in ornamentation?', 'Trill', 'Mordent', 'Appoggiatura', 'Turn', 'a'),
(4, 'Which composer famously wrote "The Four Seasons", a set of violin concertos?', 'Corelli', 'Vivaldi', 'Pachelbel', 'Albinoni', 'b'),
(4, 'What is the term for a composition that is designed to be performed by a small group of musicians, typically without a conductor?', 'Chamber music', 'Symphonic music', 'Orchestral suite', 'Solo repertoire', 'a'),
(4, 'Which instrument is known as the "king of instruments" and often associated with church music?', 'Piano', 'Violin', 'Organ', 'Trumpet', 'c'),
(4, 'What is the typical structure of a classical sonata?', 'Exposition, Development, Recapitulation', 'Theme, Variation, Recap', 'Intro, Verse, Chorus', 'A, B, C', 'a'),
(4, 'Which famous composer was a child prodigy and wrote symphonies by age 8?', 'Beethoven', 'Brahms', 'Mozart', 'Haydn', 'c'),
(4, 'In jazz, what does the term "swing" refer to?', 'A style of rhythm', 'A type of dance', 'A specific instrument', 'A musical scale', 'a'),
(4, 'What is the name of the scale that contains five notes and is often used in folk music?', 'Major scale', 'Minor scale', 'Pentatonic scale', 'Chromatic scale', 'c'),
(4, 'Which famous opera features the aria "Nessun dorma"?', 'La Bohème', 'Turandot', 'Carmen', 'Tosca', 'b'),
(4, 'What is the process of creating variations on a theme called?', 'Fugue', 'Theme and Variations', 'Imitation', 'Counterpoint', 'b'),
(4, 'Which composer is known for his minimalist style and works like "Music for 18 Musicians"?', 'Philip Glass', 'Steve Reich', 'John Adams', 'Terry Riley', 'b'),
(4, 'What is the term for a piece that combines instrumental music with vocal lines, often seen in operas?', 'Libretto', 'Orchestration', 'Recitative', 'Dramatic form', 'c'),
(4, 'Which genre of music originated in African American communities and is characterized by improvisation and syncopation?', 'Jazz', 'Blues', 'Rock', 'Classical', 'a'),
(4, 'What do the letters "A" and "B" typically refer to in musical form?', 'Themes', 'Sections', 'Instruments', 'Dynamics', 'b'),
(4, 'Which famous conductor and composer was known for his work with the New York Philharmonic and the Los Angeles Philharmonic?', 'Leonard Bernstein', 'Gustavo Dudamel', 'Daniel Barenboim', 'Herbert von Karajan', 'a'),
(4, 'What is the term for a melody sung without accompaniment?', 'A cappella', 'Accompanied', 'Solo', 'Choral', 'a'),
(4, 'Which classical composer was also an influential music theorist, known for his treatises on harmony?', 'Rameau', 'Bach', 'Beethoven', 'Debussy', 'a'),
(4, 'In a symphony, what is typically the first movement?', 'Scherzo', 'Adagio', 'Allegro', 'Andante', 'c'),
(4, 'What type of scale is often associated with Eastern music and features microtones?', 'Chromatic', 'Whole-tone', 'Pentatonic', 'Modal', 'd'),
(4, 'Which work is often cited as the first symphony written for a large orchestra?', 'Beethoven’s 9th', 'Haydn’s 104th', 'Mahler’s 1st', 'Brahms’ 1st', 'b'),
(4, 'What term describes the speed of a piece of music, often indicated by Italian terms like "Allegro" or "Adagio"?', 'Tempo', 'Dynamics', 'Texture', 'Form', 'a'),
(4, 'Which instrument is known for its distinctive sliding pitch and is commonly used in jazz ensembles?', 'Trombone', 'Trumpet', 'Saxophone', 'French Horn', 'a'),
(4, 'What is the primary difference between a concerto and a symphony?', 'Number of movements', 'Presence of a soloist', 'Orchestration', 'Style', 'b'),
(4, 'Which type of music is characterized by a call-and-response format and is often found in African American spirituals?', 'Blues', 'Jazz', 'Gospel', 'Folk', 'c'),
(4, 'What is the name of the musical form that involves the repetition of a melody with variations, often found in Baroque music?', 'Passacaglia', 'Fugue', 'Theme and Variations', 'Chaconne', 'c'),
(4, 'Who composed the famous ballet "Swan Lake"?', 'Tchaikovsky', 'Stravinsky', 'Prokofiev', 'Berlioz', 'a'),
(4, 'What is the term for a piece of music written for a solo instrument with orchestral accompaniment?', 'Sonata', 'Concerto', 'Suite', 'Fantasia', 'b'),
(4, 'In Western classical music, what is the term for a piece that tells a story through instrumental music?', 'Program music', 'Absolute music', 'Sonata form', 'Symphonic poem', 'a'),
(4, 'What is the term for the high, thin sound produced by a violin when played with a very light touch?', 'Pizzicato', 'Legato', 'Col legno', 'Sordino', 'c'),
(4, 'Which famous composer wrote "Clair de Lune"?', 'Debussy', 'Ravel', 'Chopin', 'Liszt', 'a'),
(4, 'What is the term for music that has two or more independent melodies being played simultaneously?', 'Homophony', 'Monophony', 'Polyphony', 'Chordal', 'c'),
(4, 'Which musical scale is built on a series of whole and half steps, starting from C?', 'C Major', 'C Minor', 'C Chromatic', 'C Pentatonic', 'a'),
(4, 'What is the characteristic rhythmic pattern often found in Baroque music, created by the alternation of long and short notes?', 'Fugue', 'Rhythmic motif', 'Ground bass', 'Ostinato', 'd'),
(4, 'Which famous opera includes the character of Figaro?', 'The Barber of Seville', 'Carmen', 'The Marriage of Figaro', 'Madama Butterfly', 'c'),
(4, 'What is the name of the technique where a melody is echoed or imitated in different voices or instruments?', 'Counterpoint', 'Imitation', 'Variation', 'Recapitulation', 'b'),
(4, 'What is the term for a musical composition for three performers, typically involving one instrument and two voices?', 'Trio', 'Duet', 'Quartet', 'Quintet', 'a'),
(4, 'Which form is characterized by a structure of ABA, often found in songs and instrumental pieces?', 'Binary', 'Ternary', 'Rondo', 'Through-composed', 'b'),
(4, 'What is the main purpose of a cadenza in a concerto?', 'To showcase the soloist’s skill', 'To transition between movements', 'To provide orchestral texture', 'To introduce the theme', 'a'),
(4, 'Who composed the iconic "Symphony No. 5", known for its famous four-note motif?', 'Mahler', 'Beethoven', 'Brahms', 'Dvorak', 'b'),
(4, 'In choral music, what term refers to the text of a choral work?', 'Score', 'Libretto', 'Text', 'Lyrics', 'b');

SELECT * FROM questions;


"""